### ISSUE TITLE
WinHTTrack rip of 'joelstrait.com/jssynth' hangs because 'sounds' doesn't download

### ISSUE THREAD

**Issue by GezzMC** [jstrait/jssynth#1]
Point A was pre-posting of this issue. Point B was posting this issue. I'm now at point C, and I guess GitHub doesn't allow my erasing point B after too long a period of time, so I edit it.

**Comment by GezzMC** [comment]
There's no issue, but it's nice when people set up a version of the HTML so that it can be viewed offline. Thanks.

**Comment by jstrait** [comment]
Thanks for the interest and the feedback. I’ve also thought about some of the features you suggested, and could see myself adding improvements similar to them in the future. That said, I work on this project in my free time as a hobby, so I can’t guarantee what I’m interested in adding matches up with what other people would find useful, and can’t make any promises about when/whether they would see the light of day.

I’m not familiar with WinHTTrack. At this time the project is not really intended to run offline. I added some instructions to the README for how to get it running in a local development environment though, in case that is helpful.
